### ISSUE TITLE
Add App Insights

### ISSUE THREAD

**Issue by tomhon** [simonpo/generator-botscaffold#2]
We should be encouraging partners to use as much of our Azure capability as possible. Coding in App Insights support by default is good way to drive this.
Suggest a well as coding in the require & stub for the credentials, you also include scaffold for at least 1 logging event to demonstrate how to use App Insights.

**Comment by simonpo** [comment]
Basic App Insight support added to v0.2.2 and up of the generatory, including require & credentials. 

Scaffold for one (or more) events to follow shortly

**Comment by simonpo** [comment]
eventing added. thanks for the suggestion.
